// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// Explicitly load .env file (not .env.local)
// override: true ensures it overrides any DATABASE_URL from .env.local
dotenv.config({ path: resolve(process.cwd(), ".env"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
